### ISSUE TITLE
 Please solve the problem

### ISSUE THREAD

**Issue by redbus0033** [Enzojz/ultimate_station_2#1]
![image](https://user-images.githubusercontent.com/108720002/177273696-fdc4ab98-f329-475b-9714-8d9d4949748d.png)

![image](https://user-images.githubusercontent.com/108720002/177273769-76082168-3f22-4df0-93e9-bed0a0c5d927.png)

I want to play !!! plz

**Comment by Enzojz** [comment]
I didn't know someone secretly watch this repo, but this project is always in work and not released yet
